version: '3.7'

services:
  node:
    container_name: dexlytics_node
    build: .
    tty: true
    env_file:
      - .env
    depends_on:
      - timescaledb
    volumes:
      - ./:/app
    networks:
      - dexlytics-network

  timescaledb:
    container_name: dexlyticss_timescaledb
    image: timescale/timescaledb:latest-pg13
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dexlytics-network

networks:
  dexlytics-network:
    name: dexlytics_network
    driver: bridge

volumes:
  postgres-data:
  grafana-data:
