{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Swaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last 100 Swaps",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  swaps.id AS \"ID\",\n  swaps.recipient_address AS \"Recipient address\",\n  pairs.address  AS \"Pair address\",\n  tokens0.name  AS \"Token0\",\n  tokens1.name  AS \"Token1\",\n  swaps.block_number AS \"Block number\",\n  exchanges.name AS \"Exchange\",\n  swaps.timestamp AS \"Timestamp\",\n  swaps.created_at AS \"Created at\"\nFROM swaps\nLEFT JOIN exchanges ON exchanges.id = swaps.exchange_id\nLEFT JOIN pairs AS pairs ON pairs.id = swaps.pair_id\nLEFT JOIN tokens AS tokens0 ON tokens0.id = pairs.token0_id\nLEFT JOIN tokens AS tokens1 ON tokens1.id = pairs.token1_id\nORDER BY swaps.created_at DESC\nLIMIT 100"
    }
   ]
  },
  { "title": "Pairs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Newest 100 pairs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  pairs.id AS \"ID\",\n  pairs.address AS \"Address\",\n  pairs.block_number AS \"Block Number\",\n  exchanges.name AS \"Exchange\",\n  tokens0.name AS \"Token0\",\n  tokens1.name AS \"Token1\",\n  pairs.timestamp AS \"Timestamp\",\n  pairs.created_at AS \"Created at\"\nFROM pairs\nLEFT JOIN exchanges ON exchanges.id = pairs.exchange_id\nLEFT JOIN tokens AS tokens0 ON tokens0.id = pairs.token0_id\nLEFT JOIN tokens AS tokens1 ON tokens1.id = pairs.token1_id\nORDER BY pairs.created_at DESC\nLIMIT 100"
    }
   ]
  },
  { "title": "Exchanges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Exchanges",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  id AS \"ID\",\n  key AS \"Key\",\n  name AS \"Name\",\n  platform AS \"Platform\",\n  created_at AS \"Created at\"\nFROM\n  exchanges\nORDER BY created_at DESC"
    }
   ]
  },
  {
   "title": "Newest 20 exchange pair ranges",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\n  exchange_pair_ranges.id AS \"ID\",\n  exchanges.name AS \"Exchange\",\n  exchange_pair_ranges.from_block_number AS \"From block number\",\n  exchange_pair_ranges.to_block_number AS \"To block number\",\n  exchange_pair_ranges.started_at AS \"Started at\",\n  exchange_pair_ranges.failed_at AS \"Failed at\",\n  exchange_pair_ranges.created_at AS \"Created at\",\n  exchange_pair_ranges.updated_at AS \"Updated at\"\nFROM exchange_pair_ranges\nLEFT JOIN exchanges ON exchanges.id = exchange_pair_ranges.exchange_id\nORDER BY exchange_pair_ranges.created_at DESC\nLIMIT 20"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"Count\"\nFROM errors\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Errors count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(id),\n  created_at AS \"time\"\nFROM errors\nWHERE\n  $__timeFilter(created_at)\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Newest 50 errors",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\n  id as \"ID\",\n  error AS \"Error\",\n  parameters AS \"Parameters\",\n  created_at AS \"Created at\"\nFROM\n  errors\nORDER BY id DESC\nLIMIT 50"
    }
   ]
  }
 ]
}